### PR TITLE
add kdam to show progress bar

### PR DESCRIPTION
**Pull request by Alisyaifudin**
adding kdam crate to show progress bar

### CODE REVIEW

**Comment by adamreichold** [comment]
Thank you for your contribution! I agree that having a means of reporting progress is a valuable addition. However, I am not happy about directly integrating `kdam` as proposed here. This is probably fine for a CLI application and script usage, but for example one would need to use something different in GUI application.

Could you propose something more generic like a new method on the `Execution` trait or passing in the iterator which is currently fixed as `tdqm!(0..iterations)` which would allow downstream application code to integrate their progress reporting of choice including via `kdam`?

**Comment by adamreichold** [comment]
What do you think about #2? It is admittedly much more complicated than what you proposed here, but also more general as it is not tied to a single crate for reporting progress and could be use for adaptive scheduling, e.g. until a target auto-correlation time is reached.

**Comment by Alisyaifudin** [comment]
Thank you for your extremely fast response! I like #2 more, I will close this request.

**Comment by adamreichold** [comment]
#2 was published on crates.io as v0.2.0.

**Pull request closed without merging**
